MAPS_old = [
  {
    image: "background/00_Lateinamerika.jpg",
    name: "Lateinamerika",
    x: 90,
    y: 120,
    index: 0,
    category: "Lateinamerika",
    items: [
      {
        name:"Muschel",
        indexDocument:0,
        category:"Lateinamerika",
        image:"objecte/0-LA/muschel_C.png",
        x:0,
        y:0,
        w:20,
        h:20,
        scale:1,
        purchased:false,
        active:false,
        cost:5,
      },
      {
        name:"Coconut",
        indexDocument:1,
        category:"Lateinamerika",
        image:"objecte/0-LA/Coconut_C.png",
        x:0,
        y:0,
        w:30,
        h:30,
        scale:1,
        purchased:false,
        active:false,
        cost:10,
      },
      {
        name:"Schirm",
        indexDocument:2,
        category:"Lateinamerika",
        image:"objecte/0-LA/Schirm_Comic.png",
        x:0,
        y:0,
        w:45,
        h:45,
        scale:1,
        purchased:false,
        active:false,
        cost:15,
      },
      {
        name:"Schwimmring",
        indexDocument:3,
        category:"Lateinamerika",
        image:"objecte/0-LA/Schwimmring_Comic.png",
        x:0,
        y:0,
        w:30,
        h:30,
        scale:1,
        purchased:false,
        active:false,
        cost:15,
      },
      {
        name:"Brille",
        indexDocument:4,
        category:"Lateinamerika",
        image:"objecte/0-LA/brille_C.png",
        x:0,
        y:0,
        w:20,
        h:20,
        scale:1,
        purchased:false,
        active:false,
        cost:20,
      },
      {
        name:"Volleyball",
        indexDocument:5,
        category:"Lateinamerika",
        image:"objecte/0-LA/volleyball_C.png",
        x:0,
        y:0,
        w:15,
        h:15,
        scale:1,
        purchased:false,
        active:false,
        cost:30,
      },
      {
        name:"Strandkorb",
        indexDocument:6,
        category:"Lateinamerika",
        image:"objecte/0-LA/Strandkorb_C.png",
        x:0,
        y:0,
        w:30,
        h:30,
        scale:1,
        purchased:false,
        active:false,
        cost:60,
      },
      {
        name:"Jetski",
        indexDocument:7,
        category:"Lateinamerika",
        image:"objecte/0-LA/Jetski_Comic.png",
        x:0,
        y:0,
        w:30,
        h:30,
        scale:1,
        purchased:false,
        active:false,
        cost:150,
      },
      {
        name:"Campgingbus",
        indexDocument:8,
        category:"Lateinamerika",
        image:"objecte/0-LA/Campingbus_C.png",
        x:0,
        y:0,
        w:35,
        h:35,
        scale:1,
        purchased:false,
        active:false,
        cost:200,
      },
      {
        name:"Boot",
        indexDocument:9,
        category:"Lateinamerika",
        image:"objecte/0-LA/Boot_C.png",
        x:0,
        y:0,
        w:30,
        h:30,
        scale:1,
        purchased:false,
        active:false,
        cost:250,
      }
    ],
  },
  {
    image: "background/01_Europa.jpg",
    name: "Europa",
    x: 137,
    y: 65,
    category: "Europa",
    index: 1,
    items: [
      {
        name: "Fries",
        indexDocument: 0,
        category: "Europa",
        image: "objecte/1-Europa/Fries_Z_C.png",
        x: 0,
        y: 0,
        w: 20,
        h: 20,
        scale: 1,
        purchased: false,
        active: false,
        cost: 5,
      },
     {
        name: "Big Ben",
        indexDocument: 1,
        category: "Europa",
        image: "objecte/1-Europa/Big_Ben_Comic.png",
        x: 0,
        y: 0,
        w: 50,
        h: 50,
        scale: 1,
        purchased: false,
        active: false,
        cost: 7,
      },
      {
        name: "Laterne",
        indexDocument: 2,
        category: "Europa",
        image: "objecte/1-Europa/Laterne_Z_C.png",
        x: 0,
        y: 0,
        w: 40,
        h: 40,
        scale: 1,
        purchased: false,
        active: false,
        cost: 50,
      },
      {
        name: "Garde",
        indexDocument: 3,
        category: "Europa",
        image: "objecte/1-Europa/Garde_Z_C.png",
        x: 0,
        y: 0,
        w: 30,
        h: 30,
        scale: 1,
        purchased: false,
        active: false,
        cost: 60,
      },
     {
        name: "Telefon",
        indexDocument: 4,
        category: "Europa",
        image: "objecte/1-Europa/Telefon_Z_C.png",
        x: 0,
        y: 0,
        w: 40,
        h: 40,
        scale: 1,
        purchased: false,
        active: false,
        cost: 70,
     },
     {
        name: "Bus",
        indexDocument: 5,
        category: "Europa",
        image: "objecte/1-Europa/Bus_Z_C.png",
        x: 0,
        y: 0,
        w: 25,
        h: 25,
        scale: 1,
        purchased: false,
        active: false,
        cost: 100,
     }
    ],
  },
  {
    image: "background/02_Antarktis.jpg",
    name: "Antarktis",
    x: 150,
    y: 180,
    index: 2,
    category: "Antarktis",
    items: [
      {
        name: "Schlitten",
        indexDocument: 0,
        category: "Antarktis",
        image: "objecte/2-Antarktis/Schlitten.png",
        x: 0,
        y: 0,
        w: 50,
        h: 50,
        scale: 1,
        purchased: false,
        active: false,
        cost: 15,
      },
      {
        name: "Teleskop",
        indexDocument: 1,
        category: "Antarktis",
        image: "objecte/2-Antarktis/teleskop_C.png",
        x: 0,
        y: 0,
        w: 35,
        h: 35,
        scale: 1,
        purchased: false,
        active: false,
        cost: 30,
      },
      {
        name: "Zelt",
        indexDocument: 2,
        category: "Antarktis",
        image: "objecte/2-Antarktis/zelt_C.png",
        x: 0,
        y: 0,
        w: 70,
        h: 70,
        scale: 1,
        purchased: false,
        active: false,
        cost: 40,
      },
      {
        name: "Schiff",
        indexDocument: 3,
        category: "Antarktis",
        image: "objecte/2-Antarktis/Schiff.png",
        x: 0,
        y: 0,
        w: 40,
        h: 40,
        scale: 1,
        purchased: false,
        active: false,
        cost: 100,
      },
      {
        name: "Station",
        indexDocument: 4,
        category: "Antarktis",
        image: "objecte/2-Antarktis/Station.png",
        x: 0,
        y: 0,
        w: 40,
        h: 40,
        scale: 1,
        purchased: false,
        active: false,
        cost: 200,
      },
    ],
  },
  {
    image: "background/03_Nordamerika.png",
    name: "Nordamerika",
    x: 65,
    y: 60,
    index: 3,
    category: "Nordamerika",
    items: [
      {
        name: "Auto blau",
        indexDocument: 0,
        category: "Nordamerika",
        image: "objecte/3-Nordamerika/ingo-doerrie-Fkwj-xk6yck-unsplash.png",
        x: 0,
        y: 0,
        w: 40,
        h: 40,
        scale:1,
        purchased: false,
        active: false,
        cost: 100,
      },
      {
        name: "Auto gelb",
        indexDocument: 1,
        category: "Nordamerika",
        image: "objecte/3-Nordamerika/kevin-schmid--grs8iMGqQE-unsplash.png",
        x: 0,
        y: 0,
        w: 40,
        h: 40,
        scale:1,
        purchased: false,
        active: false,
        cost: 100,
      },
    ]
  },
  {
    image: "background/04_Asien.png",
    name: "Tokyo",
    x: 200,
    y: 75,
    index: 4,
    category: "Tokyo",
    items: [
      {
        name: "Smoothie",
        indexDocument: 0,
        category: "Tokyo",
        image: "objecte/4-Asien/Smoothie_Comic.png",
        x: 0,
        y: 0,
        w: 12,
        h: 12,
        scale: 1,
        purchased: false,
        active: false,
        cost: 5,
    },
    {
        name: "Sushi",
        indexDocument: 1,
        category: "Tokyo",
        image: "objecte/4-Asien/Sushi_cut_Z_C.png",
        x: 0,
        y: 0,
        w: 12,
        h: 12,
        scale: 1,
        purchased: false,
        active: false,
        cost: 10,
      },
      {
        name: "Kamera",
        indexDocument: 2,
        category: "Tokyo",
        image: "objecte/4-Asien/Kamera_02_Z_C.png",
        x: 0,
        y: 0,
        w: 12,
        h: 12,
        scale: 1,
        purchased: false,
        active: false,
        cost: 40,
      },
      {
        name: "Rikscha",
        indexDocument: 3,
        category: "Tokyo",
        image: "objecte/4-Asien/Rikscha_Z_C.png",
        x: 0,
        y: 0,
        w: 50,
        h: 50,
        scale: 1,
        purchased: false,
        active: false,
        cost: 60,
      },
      {
        name: "Kirschbaum",
        indexDocument: 4,
        category: "Tokyo",
        image: "objecte/4-Asien/Kischbaum_Z_C.png",
        x: 0,
        y: 0,
        w: 70,
        h: 70,
        scale: 1,
        purchased: false,
        active: false,
        cost: 80,
      },
    ],
  },
  {
    image: "background/05_Australien.jpg",
    name: "Great Barrier Reef",
    x: 215,
    y: 127,
    index:5,
    category: "Australien",
    items: [
      {
        name: "Flasche",
        indexDocument: 0,
        category: "Australien",
        image: "objecte/5-Australien/Flasche_Z_C.png",
        x: 0,
        y: 0,
        w: 15,
        h: 15,
        scale: 1,
        purchased: false,
        active: false,
        cost: 7,
      },
      {
        name: "Schnorchel",
        indexDocument: 1,
        category: "Australien",
        image: "objecte/5-Australien/SchnorchelundBrille_Z_C.png",
        x: 0,
        y: 0,
        w: 15,
        h: 15,
        scale: 1,
        purchased: false,
        active: false,
        cost: 10,
      },
      {
        name: "Goldfisch",
        indexDocument: 2,
        category: "Australien",
        image: "objecte/5-Australien/Goldfisch_Z_C.png",
        x: 0,
        y: 0,
        w: 15,
        h: 15,
        scale: 1,
        purchased: false,
        active: false,
        cost: 15,
      },
      {
        name: "Seepferdchen",
        indexDocument: 3,
        category: "Australien",
        image: "objecte/5-Australien/Seepferdchen_Z_C.png",
        x: 0,
        y: 0,
        w: 15,
        h: 15,
        scale: 1,
        purchased: false,
        active: false,
        cost: 15,
      },
      {
        name: "Schildkröte",
        indexDocument: 4,
        category: "Australien",
        image: "objecte/5-Australien/Schildkroete.png",
        x: 0,
        y: 0,
        w: 30,
        h: 30,
        scale: 1,
        purchased: false,
        active: false,
        cost: 20,
      },
      {
        name: "Truhe",
        indexDocument: 5,
        category: "Australien",
        image: "objecte/5-Australien/Truhe_Z_C.png",
        x: 0,
        y: 0,
        w: 30,
        h: 30,
        scale: 1,
        purchased: false,
        active: false,
        cost: 50,
      },
      {
        name: "U-Boot",
        indexDocument: 6,
        category: "Australien",
        image: "objecte/5-Australien/uBoot_Z_C.png",
        x: 0,
        y: 0,
        w: 50,
        h: 50,
        scale: 1,
        purchased: false,
        active: false,
        cost: 200,
      },
    ],
  },
  {
    image: "background/06_Afrika.jpg",
    name: "Afrika",
    x: 145,
    y: 100,
    index: 6,
    category: "Afrika",
    items: [
      {
        name: "Kompass",
        indexDocument: 0,
        category: "Afrika",
        image: "objecte/6-Afrika/Kompass_Z_C.png",
        x: 0,
        y: 0,
        w: 12,
        h: 12,
        scale: 1,
        purchased: false,
        active: false,
        cost: 10,
      },
      {
        name: "Hängematte",
        indexDocument: 1,
        category: "Afrika",
        image: "objecte/6-Afrika/Haengematte_Z_C.png",
        x: 0,
        y: 0,
        w: 40,
        h: 40,
        scale: 1,
        purchased: false,
        active: false,
        cost: 15,
      },
      {
        name: "Zelt",
        indexDocument: 2,
        category: "Afrika",
        image: "objecte/6-Afrika/Zelt_Z_C.png",
        x: 0,
        y: 0,
        w: 40,
        h: 40,
        scale: 1,
        purchased: false,
        active: false,
        cost: 30,
      },
      {
        name: "Gnu",
        indexDocument: 3,
        category: "Afrika",
        image: "objecte/6-Afrika/Gnu_Z_C.png",
        x: 0,
        y: 0,
        w: 18,
        h: 18,
        scale: 1,
        purchased: false,
        active: false,
        cost: 40,
      },
      {
        name: "Löwe",
        indexDocument: 4,
        category: "Afrika",
        image: "objecte/6-Afrika/Loewe_Z_C.png",
        x: 0,
        y: 0,
        w: 18,
        h: 18,
        scale: 1,
        purchased: false,
        active: false,
        cost: 45,
      },
      {
        name: "Giraffe",
        indexDocument: 5,
        category: "Afrika",
        image: "objecte/6-Afrika/Giraffe_Z_C.png",
        x: 0,
        y: 0,
        w: 50,
        h: 50,
        scale: 1,
        purchased: false,
        active: false,
        cost: 50,
      },
      {
        name: "Wagen",
        indexDocument: 6,
        category: "Afrika",
        image: "objecte/6-Afrika/Wagen_02_Z_C.png",
        x: 0,
        y: 0,
        w: 40,
        h: 40,
        scale: 1,
        purchased: false,
        active: false,
        cost: 50,
      },
      {
        name: "Oase",
        indexDocument: 7,
        category: "Afrika",
        image: "objecte/6-Afrika/Oase_Z_C.png",
        x: 0,
        y: 0,
        w: 40,
        h: 40,
        scale: 1,
        purchased: false,
        active: false,
        cost: 60,
      },
      {
        name: "Elefanten",
        indexDocument: 8,
        category: "Afrika",
        image: "objecte/6-Afrika/Elefanten_Z_C.png",
        x: 0,
        y: 0,
        w: 25,
        h: 25,
        scale: 1,
        purchased: false,
        active: false,
        cost: 70,
      },
      {
        name: "Karavane",
        indexDocument: 9,
        category: "Afrika",
        image: "objecte/6-Afrika/Karavane_Z_C.png",
        x: 0,
        y: 0,
        w: 20,
        h: 20,
        scale: 1,
        purchased: false,
        active: false,
        cost: 70,
      },
    ],
  },
];
