MAPS = [
  {
    image: "background/00_Tübingen/pexels-brian-james-4524740.jpg",
    name: "Tübingen Flughafen",
    x: 155,
    y: 67,
    index: 0,
    category: "Tübingen",
    items: [
    ]
  },
  {
    image: "background/01_LA/beach-1236581.jpg",
    name: "Lateinamerika",
    x: 90,
    y: 120,
    index: 1,
    category: "Lateinamerika",
    items: [
      {
        name: "Strandkorb",
        indexDocument: 0,
        category: "Lateinamerika",
        image: "objects/01-LA/Strandkorb_C.png",
        x: 0,
        y: 0,
        w: 30,
        h: 30,
        scale: 1,
        purchased: false,
        active: false,
        cost: 95,
    },
    {
        name: "Jetski",
        indexDocument: 1,
        category: "Lateinamerika",
        image: "objects/01-LA/Jetski_Comic.png",
        x: 0,
        y: 0,
        w: 30,
        h: 30,
        scale: 1,
        purchased: false,
        active: false,
        cost: 95,
    },
    {
        name: "Campgingbus",
        indexDocument: 2,
        category: "Lateinamerika",
        image: "objects/01-LA/Campingbus_C.png",
        x: 0,
        y: 0,
        w: 35,
        h: 35,
        scale: 1,
        purchased: false,
        active: false,
        cost: 95,
    },
    {
        name: "Boot",
        indexDocument: 3,
        category: "Lateinamerika",
        image: "objects/01-LA/Boot_C.png",
        x: 0,
        y: 0,
        w: 30,
        h: 30,
        scale: 1,
        purchased: false,
        active: false,
        cost: 95,
    },
    {
        name: "Schirm",
        indexDocument: 4,
        category: "Lateinamerika",
        image: "objects/01-LA/Schirm_Comic.png",
        x: 0,
        y: 0,
        w: 45,
        h: 45,
        scale: 1,
        purchased: false,
        active: false,
        cost: 115,
    },
    {
        name: "Brille",
        indexDocument: 5,
        category: "Lateinamerika",
        image: "objects/01-LA/brille_C.png",
        x: 0,
        y: 0,
        w: 20,
        h: 20,
        scale: 1,
        purchased: false,
        active: false,
        cost: 115,
    },
    {
        name: "Coconut",
        indexDocument: 6,
        category: "Lateinamerika",
        image: "objects/01-LA/Coconut_C.png",
        x: 0,
        y: 0,
        w: 30,
        h: 30,
        scale: 1,
        purchased: false,
        active: false,
        cost: 135,
    },
    {
        name: "Schwimmring",
        indexDocument: 7,
        category: "Lateinamerika",
        image: "objects/01-LA/Schwimmring_Comic.png",
        x: 0,
        y: 0,
        w: 30,
        h: 30,
        scale: 1,
        purchased: false,
        active: false,
        cost: 135,
    },
    {
        name: "Volleyball",
        indexDocument: 8,
        category: "Lateinamerika",
        image: "objects/01-LA/volleyball_C.png",
        x: 0,
        y: 0,
        w: 15,
        h: 15,
        scale: 1,
        purchased: false,
        active: false,
        cost: 135,
    },
    {
        name: "Muschel",
        indexDocument: 9,
        category: "Lateinamerika",
        image: "objects/01-LA/muschel_C.png",
        x: 0,
        y: 0,
        w: 20,
        h: 20,
        scale: 1,
        purchased: false,
        active: false,
        cost: 195,
    }
    ],
  },
  {
    image: "background/02_Europa/02_Europa.jpg",
    name: "Europa",
    x: 135,
    y: 62,
    category: "Europa",
    index: 2,
    items: [
      {
        name: "Fries",
        indexDocument: 0,
        category: "Europa",
        image: "objects/02-Europa/Fries_Z_C.png",
        x: 0,
        y: 0,
        w: 20,
        h: 20,
        scale: 1,
        purchased: false,
        active: false,
        cost: 15,
      },
     {
        name: "Big Ben",
        indexDocument: 1,
        category: "Europa",
        image: "objects/02-Europa/Big_Ben_Comic.png",
        x: 0,
        y: 0,
        w: 50,
        h: 50,
        scale: 1,
        purchased: false,
        active: false,
        cost: 15,
      },
      {
        name: "Laterne",
        indexDocument: 2,
        category: "Europa",
        image: "objects/02-Europa/Laterne_Z_C.png",
        x: 0,
        y: 0,
        w: 40,
        h: 40,
        scale: 1,
        purchased: false,
        active: false,
        cost: 15,
      },
      {
        name: "Garde",
        indexDocument: 3,
        category: "Europa",
        image: "objects/02-Europa/Garde_Z_C.png",
        x: 0,
        y: 0,
        w: 30,
        h: 30,
        scale: 1,
        purchased: false,
        active: false,
        cost: 15,
      },
     {
        name: "Telefon",
        indexDocument: 4,
        category: "Europa",
        image: "objects/02-Europa/Telefon_Z_C.png",
        x: 0,
        y: 0,
        w: 40,
        h: 40,
        scale: 1,
        purchased: false,
        active: false,
        cost: 15,
     },
     {
        name: "Bus",
        indexDocument: 5,
        category: "Europa",
        image: "objects/02-Europa/Bus_Z_C.png",
        x: 0,
        y: 0,
        w: 25,
        h: 25,
        scale: 1,
        purchased: false,
        active: false,
        cost: 15,
     }
    ],
  },
  {
    image: "background/03_Antarktis/pexels-stein-egil-liland-1933317.png",
    name: "Antarktis",
    x: 176,
    y: 180,
    index: 3,
    category: "Antarktis",
    items: [
      {
        name: "Schlitten",
        indexDocument: 0,
        category: "Antarktis",
        image: "objects/03-Antarktis/Schlitten.png",
        x: 0,
        y: 0,
        w: 50,
        h: 50,
        scale: 1,
        purchased: false,
        active: false,
        cost: 35,
    },
    {
        name: "Teleskop",
        indexDocument: 1,
        category: "Antarktis",
        image: "objects/03-Antarktis/teleskop_C.png",
        x: 0,
        y: 0,
        w: 35,
        h: 35,
        scale: 1,
        purchased: false,
        active: false,
        cost: 35,
    },
    {
        name: "Zelt",
        indexDocument: 2,
        category: "Antarktis",
        image: "objects/03-Antarktis/zelt_C.png",
        x: 0,
        y: 0,
        w: 70,
        h: 70,
        scale: 1,
        purchased: false,
        active: false,
        cost: 35,
    },
    {
        name: "Schiff",
        indexDocument: 3,
        category: "Antarktis",
        image: "objects/03-Antarktis/Schiff.png",
        x: 0,
        y: 0,
        w: 40,
        h: 40,
        scale: 1,
        purchased: false,
        active: false,
        cost: 35,
    },
    {
        name: "Station",
        indexDocument: 4,
        category: "Antarktis",
        image: "objects/03-Antarktis/Station.png",
        x: 0,
        y: 0,
        w: 40,
        h: 40,
        scale: 1,
        purchased: false,
        active: false,
        cost: 35,
    }
    ],
  },
  {
    image: "background/04_Nordamerika/USA_Map.jpg",
    name: "Nordamerika",
    x: 65,
    y: 60,
    index: 4,
    category: "Nordamerika",
    items: [
        {
            name: "Lewis Stadium",
            indexDocument: 0,
            category: "Nordamerika",
            image: "objects/04-Nordamerika/athletes-1846039.jpg",
            x: 0,
            y: 0,
            w: 40,
            h: 40,
            scale:1,
            purchased: false,
            active: false,
            cost: 95,
        },
        {
            name: "NASA",
            indexDocument: 1,
            category: "Nordamerika",
            image: "objects/04-Nordamerika/pexels-pixabay-2166.jpg",
            x: 0,
            y: 0,
            w: 40,
            h: 40,
            scale:1,
            purchased: false,
            active: false,
            cost: 95,
        },
        {
            name: "Squaw-Mountain",
            indexDocument: 2,
            category: "Nordamerika",
            image: "objects/04-Nordamerika/squaw-mountain-4049055.jpg",
            x: 0,
            y: 0,
            w: 40,
            h: 40,
            scale:1,
            purchased: false,
            active: false,
            cost: 95,
        },
        {
            name: "Times Square",
            indexDocument: 3,
            category: "Nordamerika",
            image: "objects/04-Nordamerika/victor-he-tHdONyz_W9Y-unsplash.jpg",
            x: 0,
            y: 0,
            w: 40,
            h: 40,
            scale:1,
            purchased: false,
            active: false,
            cost: 95,
        }
    ]
  },
  {
    image: "background/05_Asien/clay-banks-hwLAI5lRhdM-unsplash.png",
    name: "Tokyo",
    x: 210,
    y: 71,
    index: 5,
    category: "Tokyo",
    items: [
      {
        name: "Sushi",
        indexDocument: 0,
        category: "Tokyo",
        image: "objects/05-Asien/Sushi_cut_Z_C.png",
        x: 0,
        y: 0,
        w: 12,
        h: 12,
        scale: 1,
        purchased: false,
        active: false,
        cost: 95,
    },
    {
        name: "Rikscha",
        indexDocument: 1,
        category: "Tokyo",
        image: "objects/05-Asien/Rikscha_Z_C.png",
        x: 0,
        y: 0,
        w: 50,
        h: 50,
        scale: 1,
        purchased: false,
        active: false,
        cost: 95,
    },
    {
        name: "Smoothie",
        indexDocument: 2,
        category: "Tokyo",
        image: "objects/05-Asien/Smoothie_Comic.png",
        x: 0,
        y: 0,
        w: 12,
        h: 12,
        scale: 1,
        purchased: false,
        active: false,
        cost: 135,
    },
    {
        name: "Kamera",
        indexDocument: 3,
        category: "Tokyo",
        image: "objects/05-Asien/Kamera_02_Z_C.png",
        x: 0,
        y: 0,
        w: 12,
        h: 12,
        scale: 1,
        purchased: false,
        active: false,
        cost: 135,
    },
    {
        name: "Kirschbaum",
        indexDocument: 4,
        category: "Tokyo",
        image: "objects/05-Asien/Kischbaum_Z_C.png",
        x: 0,
        y: 0,
        w: 70,
        h: 70,
        scale: 1,
        purchased: false,
        active: false,
        cost: 195,
    }
    ],
  },
  {
    image: "background/06_Australien/francesco-ungaro-q1lGbxF1Tsg-unsplash.jpg",
    name: "Great Barrier Reef",
    x: 215,
    y: 127,
    index: 6,
    category: "Australien",
    items: [
      {
        name: "Goldfisch",
        indexDocument: 0,
        category: "Australien",
        image: "objects/06-Australien/Goldfisch_Z_C.png",
        x: 0,
        y: 0,
        w: 15,
        h: 15,
        scale: 1,
        purchased: false,
        active: false,
        cost: 75,
    },
    {
        name: "Seepferdchen",
        indexDocument: 1,
        category: "Australien",
        image: "objects/06-Australien/Seepferdchen_Z_C.png",
        x: 0,
        y: 0,
        w: 15,
        h: 15,
        scale: 1,
        purchased: false,
        active: false,
        cost: 75,
    },
    {
        name: "Schildkröte",
        indexDocument: 2,
        category: "Australien",
        image: "objects/06-Australien/Schildkroete.png",
        x: 0,
        y: 0,
        w: 30,
        h: 30,
        scale: 1,
        purchased: false,
        active: false,
        cost: 75,
    },
    {
        name: "Flasche",
        indexDocument: 3,
        category: "Australien",
        image: "objects/06-Australien/Flasche_Z_C.png",
        x: 0,
        y: 0,
        w: 15,
        h: 15,
        scale: 1,
        purchased: false,
        active: false,
        cost: 95,
    },
    {
        name: "Truhe",
        indexDocument: 4,
        category: "Australien",
        image: "objects/06-Australien/Truhe_Z_C.png",
        x: 0,
        y: 0,
        w: 30,
        h: 30,
        scale: 1,
        purchased: false,
        active: false,
        cost: 95,
    },
    {
        name: "Schnorchel",
        indexDocument: 5,
        category: "Australien",
        image: "objects/06-Australien/SchnorchelundBrille_Z_C.png",
        x: 0,
        y: 0,
        w: 15,
        h: 15,
        scale: 1,
        purchased: false,
        active: false,
        cost: 135,
    },
    {
        name: "U-Boot",
        indexDocument: 6,
        category: "Australien",
        image: "objects/06-Australien/uBoot_Z_C.png",
        x: 0,
        y: 0,
        w: 50,
        h: 50,
        scale: 1,
        purchased: false,
        active: false,
        cost: 135,
    }
    ],
  },
  {
    image: "background/07_Afrika/07_Afrika.jpg",
    name: "Afrika",
    x: 145,
    y: 100,
    index: 7,
    category: "Afrika",
    items: [
      {
        name: "Gnu",
        indexDocument: 0,
        category: "Afrika",
        image: "objects/07-Afrika/Gnu_Z_C.png",
        x: 0,
        y: 0,
        w: 18,
        h: 18,
        scale: 1,
        purchased: false,
        active: false,
        cost: 75,
    },
    {
        name: "Wagen",
        indexDocument: 1,
        category: "Afrika",
        image: "objects/07-Afrika/Wagen_02_Z_C.png",
        x: 0,
        y: 0,
        w: 40,
        h: 40,
        scale: 1,
        purchased: false,
        active: false,
        cost: 75,
    },
    {
        name: "Hängematte",
        indexDocument: 2,
        category: "Afrika",
        image: "objects/07-Afrika/Haengematte_Z_C.png",
        x: 0,
        y: 0,
        w: 40,
        h: 40,
        scale: 1,
        purchased: false,
        active: false,
        cost: 95,
    },
    {
        name: "Giraffe",
        indexDocument: 3,
        category: "Afrika",
        image: "objects/07-Afrika/Giraffe_Z_C.png",
        x: 0,
        y: 0,
        w: 50,
        h: 50,
        scale: 1,
        purchased: false,
        active: false,
        cost: 95,
    },
    {
        name: "Elefanten",
        indexDocument: 4,
        category: "Afrika",
        image: "objects/07-Afrika/Elefanten_Z_C.png",
        x: 0,
        y: 0,
        w: 25,
        h: 25,
        scale: 1,
        purchased: false,
        active: false,
        cost: 95,
    },
    {
        name: "Kompass",
        indexDocument: 5,
        category: "Afrika",
        image: "objects/07-Afrika/Kompass_Z_C.png",
        x: 0,
        y: 0,
        w: 12,
        h: 12,
        scale: 1,
        purchased: false,
        active: false,
        cost: 115,
    },
    {
        name: "Zelt",
        indexDocument: 6,
        category: "Afrika",
        image: "objects/07-Afrika/Zelt_Z_C.png",
        x: 0,
        y: 0,
        w: 40,
        h: 40,
        scale: 1,
        purchased: false,
        active: false,
        cost: 115,
    },
    {
        name: "Löwe",
        indexDocument: 7,
        category: "Afrika",
        image: "objects/07-Afrika/Loewe_Z_C.png",
        x: 0,
        y: 0,
        w: 18,
        h: 18,
        scale: 1,
        purchased: false,
        active: false,
        cost: 115,
    },
    {
        name: "Oase",
        indexDocument: 8,
        category: "Afrika",
        image: "objects/07-Afrika/Oase_Z_C.png",
        x: 0,
        y: 0,
        w: 40,
        h: 40,
        scale: 1,
        purchased: false,
        active: false,
        cost: 115,
    },
    {
        name: "Karavane",
        indexDocument: 9,
        category: "Afrika",
        image: "objects/07-Afrika/Karavane_Z_C.png",
        x: 0,
        y: 0,
        w: 20,
        h: 20,
        scale: 1,
        purchased: false,
        active: false,
        cost: 115,
    }
    ],
  },
];
